package com.tinny.commons.helper

object CommonTextIcons {
    const val F_LOCK = "1"
    const val F_Eraser = "2"
    const val F_Translation = "4"

    const val F_Idea = "3"
    const val F_outline_checkmark = "z"
    const val F_checkmark_circle = "Z"
    const val F_trophy = "V"
    const val F_sad = "Y"
    const val F_Smile = "X"
    const val F_outline_pause = "W"
    const val F_outline_play = "U"
    const val F_BELL_RING = "T"
    const val F_BELL = "S"
    const val F_outline_heart = "R"
    const val F_heart = "Q"
    const val F_outline_star = "L"
    const val F_star = "K"
    const val F_camera = "I"
    const val F_gallery = "J"
    const val F_profile = "a"
    const val F_circle_add = "b"
    const val F_add = "c"
    const val F_alarm = "d"
    const val F_refresh = "e"
    const val F_bug = "f"
    const val F_clear = "g"
    const val F_edit = "h"
    const val F_delete = "i"
    const val F_done = "j"
    const val F_folder = "l"
    const val F_group = "m"
    const val F_outline_clear = "n"
    const val F_circle_info = "o"
    const val F_arrow_down = "p"
    const val F_arrow_left = "q"
    const val F_arrow_right = "r"
    const val F_arrow_up = "s"
    const val F_palette = "t"
    const val F_circle_pause = "u"
    const val F_ciecle_play = "y"
    const val F_pause = "v"
    const val F_play = "x"
    const val F_time = "M"
    const val F_settings = "N"
    const val F_share = "O"
    const val F_sort = "P"
    const val F_undo = "A"
    const val F_video = "C"
    const val F_list = "D"
    const val F_grid = "E"
    const val F_mute= "F"
    const val F_unmute = "G"
    const val F_home = "H"



}